name: ci-cd

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]   # v1.0.0 같은 태그 푸시 시 릴리즈 태깅
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Build (sanity)
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -ldflags="-s -w" -o backup-exporter .

      - name: Set image meta
        id: meta
        run: |
          IMAGE=think0507/backup-status-exporter
          SHA_SHORT=${GITHUB_SHA::7}
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "tags=${IMAGE}:latest,${IMAGE}:${TAG},${IMAGE}:${SHA_SHORT}" >> $GITHUB_OUTPUT
          else
            echo "tags=${IMAGE}:latest,${IMAGE}:${SHA_SHORT}" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
